# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "cmkr_for_beginners"
description = "A minimal cmkr project."

[target.hello_world]
type = "executable"
sources = ["src/**.cpp", "src/**.h"]

[target.hello_world_static_lib]
type = "static"
sources = ["lib/hello_world_static_lib/**.cpp", "lib/hello_world_static_lib/**.h"]
